### PR TITLE
INSTALL: Common Install Script and Miscellaneous Fixes

### PR DESCRIPTION
**Pull request by ironmig**
Merged #49 with current master.

### CODE REVIEW

**Comment by whispercoros** [comment]
I was still making changes on this PR.

**Comment by mattlangford** [comment]
This broke a lot of things.

**Comment by whispercoros** [comment]
This PR was never merged @mattlangford, you need to reopen #49 and close this. After that, I will check everything and let you know when it can be merged in.

**Comment by mattlangford** [comment]
I can't reopen the other since it was merged

**Pull request closed without merging**
