### PR TITLE
SHOOTER: Add check to prevent double load

### PR DESCRIPTION
**Pull request by ironmig**
Turns out ros arduino can't easily use actioniib, so for now it just keeps track of if it is loaded and won't load if it is already loaded. This of course gets broken when using manual control, but that shouldn't happen during normal autonomous operation. 

An alternative solution could be to write an additional node to run on the main boat computer which provides actionlib actions and talks to the arduino.

Also fixed some indentions to be compliant with the style guide.

### CODE REVIEW

**Comment by ironmig** [comment]
Which PR? This adds to #47

**Comment by mattlangford** [comment]
I incur lots of merge conflicts when trying to merge this in

**Comment by ironmig** [comment]
I don't understand... what are you trying to merge it into? Github says there are no conflicts

**Comment by mattlangford** [comment]
I cloned dev into a new folder and tried pulling of your PRs in and there were several merge conflicts when trying to rebase.

**Comment by ironmig** [comment]
I merged with latest dev... try now

**Comment by whispercoros** [comment]
We are still getting a build error upon merging in your branch. It seems that a file changed by @tessbianchi (gnc/navigator_perception/include/navigator_vision_lib/stereomodelfitter.h) was overwritten with old code from your fork during the merge. She has offered to help you merge this in properly tomorrow in MIL. Below is the actual error I received:

    In file included from /home/anthony/mil_ws/src/Navigator/gnc/navigator_perception    /helper/stereomodelfitter.cc:1:0:
    /home/anthony/mil_ws/src/Navigator/gnc/navigator_perception/include/navigator_vision_lib/stereomodelfitter.h:101:10: error: ‘void StereoModelFitter::decision_tree(std::vector<Eigen::Matrix<double, 3, 1> >, int, int, std::vector<int>, bool)’ cannot be overloaded
     void decision_tree(vector<Eigen::Vector3d> feature_pts_3d,
          ^
    /home/anthony/mil_ws/src/Navigator/gnc/navigator_perception/include/navigator_vision_lib/stereomodelfitter.h:86:10: error: with ‘void StereoModelFitter::decision_tree(std::vector<Eigen::Matrix<double, 3, 1> >, int, int, std::vector<int>, bool)’
     void decision_tree(vector<Eigen::Vector3d> feature_pts_3d,
          ^
    /home/anthony/mil_ws/src/Navigator/gnc/navigator_perception/include/navigator_vision_lib/stereomodelfitter.h:107:10: error: ‘void StereoModelFitter::visualize_points(std::vector<Eigen::Matrix<double, 3, 1> >, cv::Mat&)’ cannot be overloaded
     void visualize_points(std::vector<Eigen::Vector3d> feature_pts_3d,
          ^
    /home/anthony/mil_ws/src/Navigator/gnc/navigator_perception/include/navigator_vision_lib/stereomodelfitter.h:92:10: error: with ‘void StereoModelFitter::visualize_points(std::vector<Eigen::Matrix<double, 3, 1> >, cv::Mat&)’
     void visualize_points(std::vector<Eigen::Vector3d> feature_pts_3d,
          ^
    In file included from /usr/include/string.h:32:0,
                 from /usr/include/c++/4.8/cstring:42,
                 from /usr/include/boost/date_time/posix_time/conversion.hpp:12,
                 from /usr/include/boost/thread/xtime.hpp:16,
                 from /usr/include/boost/thread/pthread/mutex.hpp:17,
                 from /usr/include/boost/thread/mutex.hpp:16,
                 from /usr/include/boost/thread/pthread/thread_data.hpp:13,
                 from /usr/include/boost/thread/thread_only.hpp:17,
                 from /usr/include/boost/thread/thread.hpp:12,
                 from /usr/include/boost/thread.hpp:13,
                 from /home/anthony/mil_ws/src/Navigator/gnc/navigator_perception/include/navigator_vision_lib/stereomodelfitter.h:14,
                 from /home/anthony/mil_ws/src/Navigator/gnc/navigator_perception/helper/stereomodelfitter.cc:1:
    /home/anthony/mil_ws/src/Navigator/gnc/navigator_perception/include/navigator_vision_lib/stereomodelfitter.h:111:35: error: redeclaration of ‘cv::Mat* StereoModelFitter::current_image_left’
     cv::Mat* current_image_left = NULL;
                                   ^
    /home/anthony/mil_ws/src/Navigator/gnc/navigator_perception/include/navigator_vision_lib/stereomodelfitter.h:96:35: note: previous declaration ‘cv::Mat* StereoModelFitter::current_image_left’
     cv::Mat* current_image_left = NULL;
                                   ^
    /home/anthony/mil_ws/src/Navigator/gnc/navigator_perception/include/navigator_vision_lib/stereomodelfitter.h:112:36: error: redeclaration of ‘cv::Mat* StereoModelFitter::current_image_right’
     cv::Mat* current_image_right = NULL;
                                    ^
    /home/anthony/mil_ws/src/Navigator/gnc/navigator_perception/include/navigator_vision_lib/stereomodelfitter.h:97:36: note: previous declaration ‘cv::Mat* StereoModelFitter::current_image_right’
     cv::Mat* current_image_right = NULL;
                                    ^
    /home/anthony/mil_ws/src/Navigator/gnc/navigator_perception/include/navigator_vision_lib/stereomodelfitter.h:113:33: error: redeclaration of ‘cv::Matx34d* StereoModelFitter::left_cam_mat’
     cv::Matx34d* left_cam_mat = NULL;
                                 ^
    /home/anthony/mil_ws/src/Navigator/gnc/navigator_perception/include/navigator_vision_lib/stereomodelfitter.h:98:33: note: previous declaration ‘cv::Matx34d* StereoModelFitter::left_cam_mat’
     cv::Matx34d* left_cam_mat = NULL;
                                 ^
    /home/anthony/mil_ws/src/Navigator/gnc/navigator_perception/include/navigator_vision_lib/stereomodelfitter.h:114:34: error: redeclaration of ‘cv::Matx34d* StereoModelFitter::right_cam_mat’
     cv::Matx34d* right_cam_mat = NULL;
                                  ^
    /home/anthony/mil_ws/src/Navigator/gnc/navigator_perception/include/navigator_vision_lib/stereomodelfitter.h:99:34: note: previous declaration ‘cv::Matx34d* StereoModelFitter::right_cam_mat’
     cv::Matx34d* right_cam_mat = NULL;
                                  ^
    make[2]: *** [Navigator/gnc/navigator_perception/CMakeFiles/navigator_vision_lib.dir/helper/stereomodelfitter.cc.o] Error 1
    make[1]: *** [Navigator/gnc/navigator_perception/CMakeFiles/navigator_vision_lib.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....

**Comment by ironmig** [comment]
Take a look at the diff... two files changed both entirely contained in the shooter folder. Auto merges don't delete files and if they do it would show in the diff

**Comment by whispercoros** [comment]
Sorry about that, you are correct. We just found a very strange issue in the git history that we are working on. When this is fixed, we will have you rebase on dev and then we should be able to merge you in.

**Comment by whispercoros** [comment]
The repository appears to be fixed and is now even building on Semaphore, so once you rebase on uf-mil:dev, we should be able to merge this in.

**Pull request merged**
